### ISSUE TITLE
extract_bibliography

### ISSUE THREAD

**Issue by JaimieMurdock** [inpho/inpho#28]
Refactor `inpho.corpus.sep` to add `extract_bibliography(filename)` function that will remove the bibliography and return a list of plaintext records.

The entire bibliography can be selected in jQuery with:
```javascript
$('h2:contains('Bibliography')')
```

A Python approximation using BeautifulSoup:
```python
from BeautifulSoup import BeautifulSoup
def extract_bibliography(filename):
    with open(filename) as doc:
        soup = BeautifulSoup(doc, convertEntities=['xml', 'html']
        return soup.findAll('h2', text='Bibliography')
```

More specific processing needs to be done to parse out `<li>` or `<p>` elements into a list of records, requiring this bug report to be filed.

**Comment by rzawar** [comment]
Created function. Will discuss on it.
